name: Generate and Deploy Static Pages

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7  # Adjust to your preferred MySQL version
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp

      - name: Download WordPress and Set Up Database
        run: |
          wp core download
          wp config create --dbname=wordpress --dbuser=root --dbpass=password --dbhost=127.0.0.1 --dbprefix=wp_
          until mysqladmin ping -h 127.0.0.1 --silent; do echo "Waiting for MySQL..."; sleep 5; done
          wp core install --url="http://localhost" --title="Static WordPress" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com"

      - name: Import Database Dump
        run: wp db import .dump/wp.sql

      - name: Download and Install WP2Static
        run: |
          # Download wp2static manually from WordPress.org
          curl -L https://downloads.wordpress.org/plugin/wp2static.latest-stable.zip -o wp2static.zip
          unzip wp2static.zip -d wp-content/plugins
          wp plugin activate wp2static

      - name: Generate static files
        run: wp wp2static generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wp-content/uploads/wp2static-processed-site
          publish_branch: gh-pages
