name: Deploy WordPress Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Adjust PHP version if needed

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust Node.js version if needed

    - name: Install WP-CLI
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp

    - name: Install WP2Static plugin dependencies
      run: |
        git clone https://github.com/leonstafford/wp2static.git
        mv wp2static wp-content/plugins/wp2static
        cd wp-content/plugins/wp2static
        composer install
        npm install

    - name: Build WP2Static plugin
      run: |
        cd wp-content/plugins/wp2static
        npm run build

    - name: Setup WordPress
      run: |
        wp core download --path=/var/www/html --locale=en_US
        wp config create --path=/var/www/html --dbname=wordpress --dbuser=wp_user --dbpass=wp_pass --dbhost=localhost
        wp core install --path=/var/www/html --url=https://example.com --title="WordPress Site" --admin_user=admin --admin_password=admin_password --admin_email=admin@example.com

    - name: Install and Activate Plugins
      run: |
        wp plugin install wp2static --activate
        wp plugin activate wp2static

    - name: Deploy WordPress Site
      run: |
        # Run WP2Static to generate static files
        wp2static generate

    - name: Deploy Static Files to GitHub Pages
      uses: actions/upload-artifact@v3
      with:
        name: static-files
        path: /var/www/html/wp-content/uploads/wp2static/

    - name: Clean Up
      run: |
        sudo rm -rf /var/www/html
