name: Deploy WordPress Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
#    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, xml, curl

      - name: Install Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install WP-CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install WP2Static Plugin
        run: |
          cd wordpress/wp-content/plugins
          git clone https://github.com/wp2static/wp2static.git wp2static
          cd wp2static
          npm install
        continue-on-error: true

      - name: Build WP2Static Plugin
        run: |
          cd wordpress/wp-content/plugins/wp2static
          npm run build
        continue-on-error: true

      - name: Run WP2Static
        run: |
          cd wordpress
          wp plugin activate wp2static
          wp wp2static run --some-command  # Replace with actual WP2Static command
        env:
          WORDPRESS_CONFIG: /path/to/wordpress/config

      - name: Deploy Static Site
        run: |
          # Commands to deploy static site, e.g., using GitHub Pages
          echo "Deploying static site..."

      - name: Clean Up
        run: rm -rf wordpress/wp-content/plugins/wp2static

      - name: Notify Completion
        run: echo "Deployment Complete"
